"""
Django settings for Elesraa project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1 [::1]').split(' ')

# Needed once the app is reachable through the Cloudflare Tunnel: the tunnel
# terminates TLS and forwards plain HTTP, so Django needs to trust that
# X-Forwarded-Proto header and know which origins are allowed to POST here.
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pharmacy.apps.PharmacyConfig",
    "reports.apps.ReportsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # enforce basic auth for /reports/ urls when configured
    "Elesraa.middleware.ReportsBasicAuthMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Elesraa.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pharmacy.context_processors.guest_contact",
            ],
        },
    },
]

WSGI_APPLICATION = "Elesraa.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(BASE_DIR / "db.sqlite3"),
    },
    # Guest-submitted data (prescription requests) lives in its own file so
    # the GitHub-webhook sync of db.sqlite3 (pulled from the pharmacy PC)
    # can never overwrite/wipe it out. See pharmacy/db_router.py.
    "guest_data": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(BASE_DIR / "guest_data.sqlite3"),
    },
}

DATABASE_ROUTERS = ["pharmacy.db_router.GuestDataRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Printer settings
PRINTER_SETTINGS = {
    'PRINTER_PATH': 'Xprinter XP-D365B',  # Windows printer name
    'PRINTER_DPI': int(os.getenv('PRINTER_DPI', '203')),
    'LABEL_WIDTH': int(os.getenv('LABEL_WIDTH', '40')),
    'LABEL_HEIGHT': int(os.getenv('LABEL_HEIGHT', '25')),
}

# Static files settings
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Serves static files directly from the app (works with DEBUG=False, no
# separate nginx/reverse proxy needed for a single-instance deployment).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'pharmacy:home'
LOGOUT_REDIRECT_URL = 'pharmacy:home'

OPENAI_API_KEY = 'your-api-key-here'  # Remember to keep this secret in production
HUGGINGFACE_API_KEY = os.environ.get('HUGGINGFACE_API_KEY')

# Shared secret used to verify GitHub webhook deliveries to
# /webhook/github-data-sync/ (see pharmacy/views_webhook.py). Must match the
# secret configured on the GitHub repo's webhook settings.
GITHUB_WEBHOOK_SECRET = os.getenv('GITHUB_WEBHOOK_SECRET', '')

# Telegram bot used to notify staff of new guest prescription uploads
# (see pharmacy/telegram_utils.py). Create a bot via @BotFather and get the
# chat id by messaging the bot then visiting
# https://api.telegram.org/bot<TOKEN>/getUpdates
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

# Public base URL (no trailing slash) used to build absolute links in
# messages sent from contexts with no HTTP request, e.g. the
# remind_pending_prescriptions management command. Update this whenever the
# Cloudflare Tunnel URL changes.
PUBLIC_SITE_URL = os.getenv('PUBLIC_SITE_URL', '').rstrip('/')

# International format, no leading 0/+ (e.g. 201022815980 for Egypt), used
# to build the wa.me click-to-chat link on guest-facing pages.
WHATSAPP_NUMBER = os.getenv('WHATSAPP_NUMBER', '')

# Basic auth for /reports/ (leave empty to disable or override via env)
REPORTS_BASIC_AUTH_USER = os.getenv('REPORTS_BASIC_AUTH_USER', '')
# default password requested (you requested this value) - can be overridden via env
REPORTS_BASIC_AUTH_PASS = os.getenv('REPORTS_BASIC_AUTH_PASS', 'yarb442442')
REPORTS_BASIC_AUTH_REALM = os.getenv('REPORTS_BASIC_AUTH_REALM', 'Reports')
# TTL for reports auth (seconds). After this many seconds users will be re-challenged.
REPORTS_BASIC_AUTH_TTL = int(os.getenv('REPORTS_BASIC_AUTH_TTL', '300'))  # default 5 minutes

