version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - /dev/usb:/dev/usb  # Mount USB devices
    ports:
      - "8000:8000"
    # Windows printer access
    devices:
      - "${PRINTER_PATH:-/dev/usb/lp0}:${PRINTER_PATH:-/dev/usb/lp0}"
    privileged: true  # Needed for printer access
    # Additional Windows-specific settings
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DJANGO_SETTINGS_MODULE=Elesraa.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
