# Generated by Django 4.2.21 on 2025-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_customer_customer_type_customer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='strips_remaining',
            field=models.IntegerField(blank=True, help_text='Actual strips remaining in this entry', null=True),
        ),
    ]
