# Generated by Django 4.2.21 on 2025-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_stockentry_strips_remaining'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(fields=('medicine', 'expiration_date'), name='unique_medicine_expiration'),
        ),
    ]
