# Generated by Django 4.2.21 on 2026-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_stockentry_unique_medicine_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
