# Generated by Django 4.2.30 on 2026-07-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0010_sale_cash_given_sale_change_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guest_prescriptions/')),
                ('wants_immediate_reply', models.BooleanField(default=True, help_text='True if the guest is waiting on the page now; False if they will come back later')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied')], default='PENDING', max_length=10)),
                ('reply_text', models.TextField(blank=True)),
                ('tracking_token', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
