# Generated by Django 4.2.30 on 2026-07-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_guestprescriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprescriptionrequest',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestprescriptionrequest',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
