# Generated by Django 4.2.30 on 2026-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_guestprescriptionrequest_last_reminded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprescriptionrequest',
            name='replied_by',
        ),
        migrations.AddField(
            model_name='guestprescriptionrequest',
            name='replied_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
